<ul class="nav <?= $class ?> menu-<?= $menukey ?>">
    <?php if($menu): ?>
        <?php $count=1; ?>
        <?php foreach($menu as $item):?>

            <?php $ajax = ((substr($item['link'], 0, 7) == 'http://') || (substr($item['link'], 0, 8) == 'https://')) ? '' : 'ajax'?>


            <?php if($item['link'] && $item['sub'] && count($item['sub'])): ?>

                <?php // Item with link and caret with dropdown ?>
                <li class="menu-<?=$menukey ?>-item-<?= $count; ?> dropdown link-and-dropdown">

                    <a  class="<?= $ajax ?> menu-link"
                        href="<?= $item['link'];?>"
                        <?php if($item['target']):?>target="<?= $item['target']?>"<? endif; ?>
                        <?php if($item['title']):?>title="<?= $item['title']?>"<? endif; ?>
                        >
                        <?= $item['name'] ?>
                    </a><a  class="dropdown-toggle menu-dropdown" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                        <?php if($item['title']):?>title="<?= $item['title']?>"<? endif; ?>
                        >
                        <span class="caret"></span>
                    </a>

                    <ul class="dropdown-menu">
                        <?php foreach($item['sub'] as $sub):?>

                            <?php $ajax2 = ((substr($sub['link'], 0, 7) == 'http://') || (substr($sub['link'], 0, 8) == 'https://')) ? '' : 'ajax'?>
                            <li>
                                <a  class="<?= $ajax2 ?> menu-link"
                                    href="<?= $sub['link'];?>"
                                    <?php if($sub['target']):?>target="<?= $sub['target']?>"<? endif; ?>
                                    <?php if($sub['title']):?>title="<?= $sub['title']?>"<? endif; ?>
                                    >
                                    <?= $sub['name'] ?>
                                </a>
                            </li>

                        <?php endforeach; ?>
                    </ul>
                </li>

            <?php elseif($item['sub'] && count($item['sub'])): ?>

                <?php // Item with dropdown ?>
                <li class="menu-<?=$menukey ?>-item-<?= $count; ?> dropdown">

                    <a  class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                        <?php if($item['title']):?>title="<?= $item['title']?>"<? endif; ?>
                        >
                        <?= $item['name'] ?>
                    </a>

                    <ul class="dropdown-menu">
                        <?php foreach($item['sub'] as $sub):?>

                            <?php $ajax2 = ((substr($sub['link'], 0, 7) == 'http://') || (substr($sub['link'], 0, 8) == 'https://')) ? '' : 'ajax'?>
                            <li>
                                <a  class="<?= $ajax2 ?> menu-link"
                                    href="<?= $sub['link'];?>"
                                    <?php if($sub['target']):?>target="<?= $sub['target']?>"<? endif; ?>
                                    <?php if($sub['title']):?>title="<?= $sub['title']?>"<? endif; ?>
                                    >
                                    <?= $sub['name'] ?>
                                </a>
                            </li>

                        <?php endforeach; ?>
                    </ul>

                </li>

            <?php elseif($item['link']): ?>

                <?php // Item without dropdown ?>
                <li class="menu-<?=$menukey ?>-item-<?= $count; ?>">

                    <a  class="<?= $ajax ?>"
                        href="<?= $item['link'];?>"
                         <?php if($item['target']):?>target="<?= $item['target']?>"<? endif; ?>
                        <?php if($item['title']):?>title="<?= $item['title']?>"<? endif; ?>
                    >
                        <?= $item['name'] ?>
                    </a>

                </li>

            <?php else: ?>

                <?php // disabled item ?>
                <li class="disabled menu-<?=$menukey ?>-item-<?= $count; ?>">

                    <a
                        <?php if($item['title']):?>title="<?= $item['title']?>"<? endif; ?>
                        >
                        <?= $item['name'] ?>
                    </a>

                </li>

            <?php endif; ?>

        <?php $count++; ?>
        <?php endforeach; ?>
    <?php else: ?>
        <li class="bg-danger">
            <a>Menu "<?= $menukey ?>" not found!</a>
        </li>
    <?php endif; ?>
</ul>